import { PropertyCardData } from "@/components/ui/Card/property-card"

export const propertiesData: PropertyCardData[] = [
    {
        id: "castellon-3",
        name: "Castellon 3",
        location: "Castellón, España",
        price: "€284.800",
        currency: "EUR",
        image: "/luxury-residential-property-miami-florida.jpg",
        status: "Financiado",
        investmentPeriod: "4 años",
        totalReturn: "42.00%",
        annualReturn: "10.5%",
        rentalStart: "09/10/2025",
        returnType: "Rendimiento final",
        minInvestment: "$1,000",
        tokenPrice: "100 €",
        capitalGain: "4.52%",
        totalAPY: "10.06%",
        yields: "0.00%",
        description:
            "Rental vuelve a apostar por la inversión en España y lo hace en la ciudad de Castellón. Presentamos nuestro nuevo proyecto en el corazón de esta ciudad valenciana, a la que volvemos tras un año, con un inmueble situado en la Ronda Magdalena, 63. No pierdas la oportunidad de invertir en él obteniendo unos ingresos pasivos y una rentabilidad atractiva.\n\nEsta vivienda se destinará al alquiler por habitaciones y ha sido diseñada pensando en la comodidad y convivencia de sus inquilinos. Consta de 8 habitaciones, 1 cocina totalmente equipada y 4 baños, además de una amplia zona común, todo distribuido en 215 metros cuadrados. Cada espacio ha sido cuidadosamente pensado para proporcionar un ambiente acogedor y funcional. La cocina está equipada con todos los electrodomésticos modernos que se puedan necesitar. Los 4 baños garantizan que nunca tendrán que esperar para usar las instalaciones, y la espaciosa zona común brindará un lugar ideal para socializar.",
    },
    {
        id: "valencia-12",
        name: "Valencia 12",
        location: "Valencia, España",
        price: "€1.152.800",
        currency: "EUR",
        image: "/modern-apartment-building-valencia-spain.jpg",
        status: "Financiado",
        investmentPeriod: "3 años",
        totalReturn: "36.00%",
        annualReturn: "12%",
        rentalStart: "31/07/2028",
        returnType: "Rendimiento final",
        minInvestment: "$2,500",
        tokenPrice: "150 €",
        capitalGain: "5.20%",
        totalAPY: "12.00%",
        yields: "0.00%",
        description: "Proyecto residencial moderno en el corazón de Valencia con excelentes perspectivas de rentabilidad.",
    },
    {
        id: "proyecto-100",
        name: "Proyecto 100",
        location: "Dubai, Emiratos Árabes",
        price: "$5.150.000",
        currency: "USD",
        image: "/luxury-skyscraper-dubai-sunset.jpg",
        status: "Financiado",
        investmentPeriod: "10 meses",
        totalReturn: "9.26%",
        annualReturn: "11.11%",
        rentalStart: "13/04/2026",
        returnType: "Rendimiento mensual + final",
        minInvestment: "$5,000",
        tokenPrice: "200 $",
        capitalGain: "3.80%",
        totalAPY: "11.11%",
        yields: "0.50%",
        description: "Rascacielos de lujo en Dubai con vistas panorámicas y retorno de inversión acelerado.",
    },
    {
        id: "samana-2",
        name: "Samaná 2",
        location: "Samaná, República Dominicana",
        price: "$1.000.000",
        currency: "USD",
        image: "/beachfront-resort-property-caribbean.jpg",
        status: "Financiado",
        investmentPeriod: "3 años",
        totalReturn: "37.50%",
        annualReturn: "12.5%",
        rentalStart: "15/10/2025",
        returnType: "Rendimiento final",
        minInvestment: "$1,500",
        tokenPrice: "120 $",
        capitalGain: "4.75%",
        totalAPY: "12.50%",
        yields: "0.00%",
        description: "Resort de playa en Samaná con potencial de rentabilidad excepcional.",
    },
    {
        id: "barcelona-premium",
        name: "Barcelona Premium",
        location: "Barcelona, España",
        price: "€2.500.000",
        currency: "EUR",
        image: "/luxury-penthouse-barcelona-city-view.jpg",
        status: "En Financiamiento",
        investmentPeriod: "5 años",
        totalReturn: "45.00%",
        annualReturn: "9%",
        rentalStart: "01/01/2026",
        returnType: "Rendimiento final",
        minInvestment: "$3,000",
        tokenPrice: "250 €",
        capitalGain: "6.10%",
        totalAPY: "9.00%",
        yields: "0.00%",
        description: "Ático de lujo en Barcelona con vistas a la ciudad y acceso a servicios premium.",
    },
    {
        id: "madrid-centro",
        name: "Madrid Centro",
        location: "Madrid, España",
        price: "€850.000",
        currency: "EUR",
        image: "/modern-apartment-madrid-center.jpg",
        status: "Disponible",
        investmentPeriod: "6 años",
        totalReturn: "54.00%",
        annualReturn: "9%",
        rentalStart: "15/03/2026",
        returnType: "Rendimiento final",
        minInvestment: "$2,000",
        tokenPrice: "175 €",
        capitalGain: "5.80%",
        totalAPY: "9.00%",
        yields: "0.00%",
        description: "Apartamento moderno en el corazón de Madrid, ubicado en una zona privilegiada con alta demanda de alquiler. La propiedad cuenta con acabados de primera calidad y está completamente amueblada para maximizar el retorno de inversión.",
    },
    {
        id: "miami-beach",
        name: "Miami Beach Resort",
        location: "Miami, Estados Unidos",
        price: "$3.200.000",
        currency: "USD",
        image: "/luxury-beachfront-condo-miami.jpg",
        status: "Financiado",
        investmentPeriod: "4 años",
        totalReturn: "48.00%",
        annualReturn: "12%",
        rentalStart: "01/06/2025",
        returnType: "Rendimiento mensual + final",
        minInvestment: "$8,000",
        tokenPrice: "400 $",
        capitalGain: "6.50%",
        totalAPY: "12.00%",
        yields: "1.20%",
        description: "Condominio de lujo frente al mar en Miami Beach con acceso directo a la playa. Cuenta con amenidades de clase mundial incluyendo spa, gimnasio, piscina infinita y servicio de conserjería 24/7.",
    },
    {
        id: "lisbon-historic",
        name: "Lisboa Histórico",
        location: "Lisboa, Portugal",
        price: "€650.000",
        currency: "EUR",
        image: "/historic-building-lisbon-portugal.jpg",
        status: "En Financiamiento",
        investmentPeriod: "5 años",
        totalReturn: "50.00%",
        annualReturn: "10%",
        rentalStart: "20/08/2026",
        returnType: "Rendimiento final",
        minInvestment: "$1,800",
        tokenPrice: "130 €",
        capitalGain: "5.50%",
        totalAPY: "10.00%",
        yields: "0.00%",
        description: "Edificio histórico completamente renovado en el centro de Lisboa, combinando el encanto tradicional portugués con comodidades modernas. Ubicado en una zona turística de alta demanda.",
    },
    {
        id: "tokyo-shibuya",
        name: "Tokyo Shibuya Tower",
        location: "Tokio, Japón",
        price: "¥180.000.000",
        currency: "JPY",
        image: "/modern-tower-tokyo-shibuya.jpg",
        status: "Disponible",
        investmentPeriod: "7 años",
        totalReturn: "63.00%",
        annualReturn: "9%",
        rentalStart: "10/11/2026",
        returnType: "Rendimiento final",
        minInvestment: "$4,500",
        tokenPrice: "300 ¥",
        capitalGain: "7.20%",
        totalAPY: "9.00%",
        yields: "0.00%",
        description: "Torre residencial de última generación en el corazón de Shibuya, uno de los distritos más dinámicos de Tokio. Ofrece tecnología inteligente integrada y vistas panorámicas de la ciudad.",
    },
]

// Helper function to get property by ID
export function getPropertyById(id: string): PropertyCardData | undefined {
    return propertiesData.find(property => property.id === id)
}

// Helper function to get properties by status
export function getPropertiesByStatus(status: PropertyCardData['status']): PropertyCardData[] {
    return propertiesData.filter(property => property.status === status)
}